server:
  port: 9002
spring:
  application:
    name: jdbcTemplate
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    password: root
    username: root
#    jndi-name: java:jboss/datasources/customers
