server:
  port: 9002
spring:
  application:
    name: jdbcTemplate
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8
    password: root
    username: root
#    jndi-name: java:jboss/datasources/customers
