server:
  port: 8088

#thymeleaf默认配置
spring:
  thymeleaf:
    cache: true
    check-template: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    #    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    async:
      request-timeout: 4000
#    template-resolver-order:

