mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
spring:
  datasource:
    test1:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8
    test2:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8