spring:
  profiles:
    active: dev

com:
  answer:
    blog:
      name: answer blog
      title: Spring boot 教程
      desc: ${com.answer.blog.name} 正在写博客 ${com.answer.blog.title}
      value: ${random.value}
      number: ${random.int}
      bignumber: ${random.long}
      test1: ${random.int(10)}
      test2: ${random.int[10,20]}